;track ids
.ENUM
	track_title
	track_needleman
	track_magnetman
	track_geminiman
	track_hardman
	track_topman
	track_snakeman
	track_sparkman
	track_shadowman
	track_wily1_2
	track_wily3_4
	track_wily5_6
	track_boss_fighting
	track_wily_boss_fighting
	track_password
	track_staff_roll
	track_stage_select
	track_protoman_whistle
	track_ending
	track_landing
	track_1up
	track_mega_buster
	track_megaman_hit
	track_death
	track_enemy_hit
	track_enemy_immune
	track_open_menu
	track_select
	track_refill
	track_door
	track_cannon
	track_jump_into_water
	track_bikky
	track_21
	track_wanaan
	track_appearing_block
	track_nitron
	track_bolton_and_nutton
	track_elecn
	track_explosion
	track_wily_ufo
	track_29
	track_magnet_missile
	track_gemini_laser
	track_top_spin
	track_spark_shock
	track_shadow_blade
	track_2f
	track_hardman_slam
	track_menu_fade_out
	track_get_weapon_energy
	track_boss_show
	track_teleport_out
	track_get_weapon
	track_wily_castle
	track_wily_defeated
	track_boss_defeated
.ENDENUM
