track_pointers:
	.DBYT music_title
	.DBYT music_needleman
	.DBYT music_magnetman
	.DBYT music_geminiman
	.DBYT music_hardman
	.DBYT music_topman
	.DBYT music_snakeman
	.DBYT music_sparkman
	.DBYT music_shadowman
	.DBYT music_wily1_2
	.DBYT music_wily3_4
	.DBYT music_wily5_6
	.DBYT music_boss_fighting
	.DBYT music_wily_boss_fighting
	.DBYT music_password
	.DBYT music_staff_roll
	.DBYT music_stage_select
	.DBYT music_protoman_whistle
	.DBYT music_ending
	.DBYT sfx_landing
	.DBYT sfx_1up
	.DBYT sfx_mega_buster
	.DBYT sfx_megaman_hit
	.DBYT sfx_death
	.DBYT sfx_enemy_hit
	.DBYT sfx_enemy_immune
	.DBYT sfx_open_menu
	.DBYT sfx_select
	.DBYT sfx_refill
	.DBYT sfx_door
	.DBYT sfx_cannon
	.DBYT sfx_jump_into_water
	.DBYT sfx_bikky
	.DBYT sfx_21
	.DBYT sfx_wanaan
	.DBYT sfx_appearing_block
	.DBYT sfx_nitron
	.DBYT sfx_bolton_and_nutton
	.DBYT sfx_elecn
	.DBYT sfx_explosion
	.DBYT sfx_wily_ufo
	.DBYT sfx_29
	.DBYT sfx_magnet_missile
	.DBYT sfx_gemini_laser
	.DBYT sfx_top_spin
	.DBYT sfx_spark_shock
	.DBYT sfx_shadow_blade
	.DBYT sfx_2f
	.DBYT sfx_hardman_slam
	.DBYT sfx_menu_fade_out
	.DBYT sfx_get_weapon_energy
	.DBYT music_boss_show
	.DBYT sfx_teleport_out
	.DBYT music_get_weapon
	.DBYT music_wily_castle
	.DBYT music_wily_defeated
	.DBYT music_boss_defeated
track_pointers_end:
