oam_frameset_lo_pointers:
	.LOBYTES oam_frameset_00
	.LOBYTES oam_frameset_01
	.LOBYTES oam_frameset_02
	.LOBYTES oam_frameset_03
	.LOBYTES oam_frameset_04
	.LOBYTES oam_frameset_05
	.LOBYTES oam_frameset_06
	.LOBYTES oam_frameset_07
	.LOBYTES oam_frameset_08
	.LOBYTES oam_frameset_09
	.LOBYTES oam_frameset_0a
	.LOBYTES oam_frameset_0b
	.LOBYTES oam_frameset_0c
	.LOBYTES oam_frameset_0d
	.LOBYTES oam_frameset_0e
	.LOBYTES oam_frameset_0f
	.LOBYTES oam_frameset_10
	.LOBYTES oam_frameset_11
	.LOBYTES oam_frameset_12
	.LOBYTES oam_frameset_13
	.LOBYTES oam_frameset_14
	.LOBYTES oam_frameset_15
	.LOBYTES oam_frameset_16
	.LOBYTES oam_frameset_17
	.LOBYTES oam_frameset_18
	.LOBYTES oam_frameset_19
	.LOBYTES oam_frameset_1a
	.LOBYTES oam_frameset_1b
	.LOBYTES oam_frameset_1c
	.LOBYTES oam_frameset_1d
	.LOBYTES oam_frameset_1e
	.LOBYTES oam_frameset_1f
	.LOBYTES oam_frameset_20
	.LOBYTES oam_frameset_21
	.LOBYTES oam_frameset_22
	.LOBYTES oam_frameset_23
	.LOBYTES oam_frameset_24
	.LOBYTES oam_frameset_25
	.LOBYTES oam_frameset_26
	.LOBYTES oam_frameset_27
	.LOBYTES oam_frameset_28
	.LOBYTES oam_frameset_29
	.LOBYTES oam_frameset_2a
	.LOBYTES oam_frameset_2b
	.LOBYTES oam_frameset_2c
	.LOBYTES oam_frameset_2d
	.LOBYTES oam_frameset_2e
	.LOBYTES oam_frameset_2f
	.LOBYTES oam_frameset_30
	.LOBYTES oam_frameset_31
	.LOBYTES oam_frameset_32
	.LOBYTES oam_frameset_33
	.LOBYTES oam_frameset_34
	.LOBYTES oam_frameset_35
	.LOBYTES oam_frameset_36
	.LOBYTES oam_frameset_37
	.LOBYTES oam_frameset_38
	.LOBYTES oam_frameset_39
	.LOBYTES oam_frameset_3a
	.LOBYTES oam_frameset_3b
	.LOBYTES oam_frameset_3c
	.LOBYTES oam_frameset_3d
	.LOBYTES oam_frameset_3e
	.LOBYTES oam_frameset_3f
	.LOBYTES oam_frameset_40
	.LOBYTES oam_frameset_41
	.LOBYTES oam_frameset_42
	.LOBYTES oam_frameset_43
	.LOBYTES oam_frameset_44
	.LOBYTES oam_frameset_45
	.LOBYTES oam_frameset_46
	.LOBYTES oam_frameset_47
	.LOBYTES oam_frameset_48
	.LOBYTES oam_frameset_49
	.LOBYTES oam_frameset_4a
	.LOBYTES oam_frameset_4b
	.LOBYTES oam_frameset_4c
	.LOBYTES oam_frameset_4d
	.LOBYTES oam_frameset_4e
	.LOBYTES oam_frameset_4f
	.LOBYTES oam_frameset_50
	.LOBYTES oam_frameset_51
	.LOBYTES oam_frameset_52
	.LOBYTES oam_frameset_53
	.LOBYTES oam_frameset_54
	.LOBYTES oam_frameset_55
	.LOBYTES oam_frameset_56
	.LOBYTES oam_frameset_57
	.LOBYTES oam_frameset_58
	.LOBYTES oam_frameset_59
	.LOBYTES oam_frameset_5a
	.LOBYTES oam_frameset_5b
	.LOBYTES oam_frameset_5c
	.LOBYTES oam_frameset_5d
	.LOBYTES oam_frameset_5e
	.LOBYTES oam_frameset_5f
	.LOBYTES oam_frameset_60
	.LOBYTES oam_frameset_61
	.LOBYTES oam_frameset_62
	.LOBYTES oam_frameset_63
	.LOBYTES oam_frameset_64
	.LOBYTES oam_frameset_65
	.LOBYTES oam_frameset_66
	.LOBYTES oam_frameset_67
	.LOBYTES oam_frameset_68
	.LOBYTES oam_frameset_69
	.LOBYTES oam_frameset_6a
	.LOBYTES oam_frameset_6b
	.LOBYTES oam_frameset_6c
	.LOBYTES oam_frameset_6d
	.LOBYTES oam_frameset_6e
	.LOBYTES oam_frameset_6f
	.LOBYTES oam_frameset_70
	.LOBYTES oam_frameset_71
	.LOBYTES oam_frameset_72
	.LOBYTES oam_frameset_73
	.LOBYTES oam_frameset_74
	.LOBYTES oam_frameset_75
	.LOBYTES oam_frameset_76
	.LOBYTES oam_frameset_77
	.LOBYTES oam_frameset_78
	.LOBYTES oam_frameset_79
	.LOBYTES oam_frameset_7a
	.LOBYTES oam_frameset_7b
	.LOBYTES oam_frameset_7c
	.LOBYTES oam_frameset_7d
	.LOBYTES oam_frameset_7e
	.LOBYTES oam_frameset_7f

oam_frameset_hi_pointers:
	.HIBYTES oam_frameset_00
	.HIBYTES oam_frameset_01
	.HIBYTES oam_frameset_02
	.HIBYTES oam_frameset_03
	.HIBYTES oam_frameset_04
	.HIBYTES oam_frameset_05
	.HIBYTES oam_frameset_06
	.HIBYTES oam_frameset_07
	.HIBYTES oam_frameset_08
	.HIBYTES oam_frameset_09
	.HIBYTES oam_frameset_0a
	.HIBYTES oam_frameset_0b
	.HIBYTES oam_frameset_0c
	.HIBYTES oam_frameset_0d
	.HIBYTES oam_frameset_0e
	.HIBYTES oam_frameset_0f
	.HIBYTES oam_frameset_10
	.HIBYTES oam_frameset_11
	.HIBYTES oam_frameset_12
	.HIBYTES oam_frameset_13
	.HIBYTES oam_frameset_14
	.HIBYTES oam_frameset_15
	.HIBYTES oam_frameset_16
	.HIBYTES oam_frameset_17
	.HIBYTES oam_frameset_18
	.HIBYTES oam_frameset_19
	.HIBYTES oam_frameset_1a
	.HIBYTES oam_frameset_1b
	.HIBYTES oam_frameset_1c
	.HIBYTES oam_frameset_1d
	.HIBYTES oam_frameset_1e
	.HIBYTES oam_frameset_1f
	.HIBYTES oam_frameset_20
	.HIBYTES oam_frameset_21
	.HIBYTES oam_frameset_22
	.HIBYTES oam_frameset_23
	.HIBYTES oam_frameset_24
	.HIBYTES oam_frameset_25
	.HIBYTES oam_frameset_26
	.HIBYTES oam_frameset_27
	.HIBYTES oam_frameset_28
	.HIBYTES oam_frameset_29
	.HIBYTES oam_frameset_2a
	.HIBYTES oam_frameset_2b
	.HIBYTES oam_frameset_2c
	.HIBYTES oam_frameset_2d
	.HIBYTES oam_frameset_2e
	.HIBYTES oam_frameset_2f
	.HIBYTES oam_frameset_30
	.HIBYTES oam_frameset_31
	.HIBYTES oam_frameset_32
	.HIBYTES oam_frameset_33
	.HIBYTES oam_frameset_34
	.HIBYTES oam_frameset_35
	.HIBYTES oam_frameset_36
	.HIBYTES oam_frameset_37
	.HIBYTES oam_frameset_38
	.HIBYTES oam_frameset_39
	.HIBYTES oam_frameset_3a
	.HIBYTES oam_frameset_3b
	.HIBYTES oam_frameset_3c
	.HIBYTES oam_frameset_3d
	.HIBYTES oam_frameset_3e
	.HIBYTES oam_frameset_3f
	.HIBYTES oam_frameset_40
	.HIBYTES oam_frameset_41
	.HIBYTES oam_frameset_42
	.HIBYTES oam_frameset_43
	.HIBYTES oam_frameset_44
	.HIBYTES oam_frameset_45
	.HIBYTES oam_frameset_46
	.HIBYTES oam_frameset_47
	.HIBYTES oam_frameset_48
	.HIBYTES oam_frameset_49
	.HIBYTES oam_frameset_4a
	.HIBYTES oam_frameset_4b
	.HIBYTES oam_frameset_4c
	.HIBYTES oam_frameset_4d
	.HIBYTES oam_frameset_4e
	.HIBYTES oam_frameset_4f
	.HIBYTES oam_frameset_50
	.HIBYTES oam_frameset_51
	.HIBYTES oam_frameset_52
	.HIBYTES oam_frameset_53
	.HIBYTES oam_frameset_54
	.HIBYTES oam_frameset_55
	.HIBYTES oam_frameset_56
	.HIBYTES oam_frameset_57
	.HIBYTES oam_frameset_58
	.HIBYTES oam_frameset_59
	.HIBYTES oam_frameset_5a
	.HIBYTES oam_frameset_5b
	.HIBYTES oam_frameset_5c
	.HIBYTES oam_frameset_5d
	.HIBYTES oam_frameset_5e
	.HIBYTES oam_frameset_5f
	.HIBYTES oam_frameset_60
	.HIBYTES oam_frameset_61
	.HIBYTES oam_frameset_62
	.HIBYTES oam_frameset_63
	.HIBYTES oam_frameset_64
	.HIBYTES oam_frameset_65
	.HIBYTES oam_frameset_66
	.HIBYTES oam_frameset_67
	.HIBYTES oam_frameset_68
	.HIBYTES oam_frameset_69
	.HIBYTES oam_frameset_6a
	.HIBYTES oam_frameset_6b
	.HIBYTES oam_frameset_6c
	.HIBYTES oam_frameset_6d
	.HIBYTES oam_frameset_6e
	.HIBYTES oam_frameset_6f
	.HIBYTES oam_frameset_70
	.HIBYTES oam_frameset_71
	.HIBYTES oam_frameset_72
	.HIBYTES oam_frameset_73
	.HIBYTES oam_frameset_74
	.HIBYTES oam_frameset_75
	.HIBYTES oam_frameset_76
	.HIBYTES oam_frameset_77
	.HIBYTES oam_frameset_78
	.HIBYTES oam_frameset_79
	.HIBYTES oam_frameset_7a
	.HIBYTES oam_frameset_7b
	.HIBYTES oam_frameset_7c
	.HIBYTES oam_frameset_7d
	.HIBYTES oam_frameset_7e
	.HIBYTES oam_frameset_7f
