oam_sprites_lo_pointers:
	.LOBYTES oam_sprites_00
	.LOBYTES oam_sprites_01
	.LOBYTES oam_sprites_02
	.LOBYTES oam_sprites_03
	.LOBYTES oam_sprites_04
	.LOBYTES oam_sprites_05
	.LOBYTES oam_sprites_06
	.LOBYTES oam_sprites_07
	.LOBYTES oam_sprites_08
	.LOBYTES oam_sprites_09
	.LOBYTES oam_sprites_0a
	.LOBYTES oam_sprites_0b
	.LOBYTES oam_sprites_0c
	.LOBYTES oam_sprites_0d
	.LOBYTES oam_sprites_0e
	.LOBYTES oam_sprites_0f
	.LOBYTES oam_sprites_10
	.LOBYTES oam_sprites_11
	.LOBYTES oam_sprites_12
	.LOBYTES oam_sprites_13
	.LOBYTES oam_sprites_14
	.LOBYTES oam_sprites_15
	.LOBYTES oam_sprites_16
	.LOBYTES oam_sprites_17
	.LOBYTES oam_sprites_18
	.LOBYTES oam_sprites_19
	.LOBYTES oam_sprites_1a
	.LOBYTES oam_sprites_1b
	.LOBYTES oam_sprites_1c
	.LOBYTES oam_sprites_1d
	.LOBYTES oam_sprites_1e
	.LOBYTES oam_sprites_1f
	.LOBYTES oam_sprites_20
	.LOBYTES oam_sprites_21
	.LOBYTES oam_sprites_22
	.LOBYTES oam_sprites_23
	.LOBYTES oam_sprites_24
	.LOBYTES oam_sprites_25
	.LOBYTES oam_sprites_26
	.LOBYTES oam_sprites_27
	.LOBYTES oam_sprites_28
	.LOBYTES oam_sprites_29
	.LOBYTES oam_sprites_2a
	.LOBYTES oam_sprites_2b
	.LOBYTES oam_sprites_2c
	.LOBYTES oam_sprites_2d
	.LOBYTES oam_sprites_2e
	.LOBYTES oam_sprites_2f
	.LOBYTES oam_sprites_30
	.LOBYTES oam_sprites_31
	.LOBYTES oam_sprites_32
	.LOBYTES oam_sprites_33
	.LOBYTES oam_sprites_34
	.LOBYTES oam_sprites_35
	.LOBYTES oam_sprites_36
	.LOBYTES oam_sprites_37
	.LOBYTES oam_sprites_38
	.LOBYTES oam_sprites_39
	.LOBYTES oam_sprites_3a
	.LOBYTES oam_sprites_3b
	.LOBYTES oam_sprites_3c
	.LOBYTES oam_sprites_3d
	.LOBYTES oam_sprites_3e
	.LOBYTES oam_sprites_3f
	.LOBYTES oam_sprites_40
	.LOBYTES oam_sprites_41
	.LOBYTES oam_sprites_42
	.LOBYTES oam_sprites_43
	.LOBYTES oam_sprites_44
	.LOBYTES oam_sprites_45
	.LOBYTES oam_sprites_46
	.LOBYTES oam_sprites_47
	.LOBYTES oam_sprites_48
	.LOBYTES oam_sprites_49
	.LOBYTES oam_sprites_4a
	.LOBYTES oam_sprites_4b
	.LOBYTES oam_sprites_4c
	.LOBYTES oam_sprites_4d
	.LOBYTES oam_sprites_4e
	.LOBYTES oam_sprites_4f
	.LOBYTES oam_sprites_50
	.LOBYTES oam_sprites_51
	.LOBYTES oam_sprites_52
	.LOBYTES oam_sprites_53
	.LOBYTES oam_sprites_54
	.LOBYTES oam_sprites_55
	.LOBYTES oam_sprites_56
	.LOBYTES oam_sprites_57
	.LOBYTES oam_sprites_58
	.LOBYTES oam_sprites_59
	.LOBYTES oam_sprites_5a
	.LOBYTES oam_sprites_5b
	.LOBYTES oam_sprites_5c
	.LOBYTES oam_sprites_5d
	.LOBYTES oam_sprites_5e
	.LOBYTES oam_sprites_5f
	.LOBYTES oam_sprites_60
	.LOBYTES oam_sprites_61
	.LOBYTES oam_sprites_62
	.LOBYTES oam_sprites_63
	.LOBYTES oam_sprites_64
	.LOBYTES oam_sprites_65
	.LOBYTES oam_sprites_66
	.LOBYTES oam_sprites_67
	.LOBYTES oam_sprites_68
	.LOBYTES oam_sprites_69
	.LOBYTES oam_sprites_6a
	.LOBYTES oam_sprites_6b
	.LOBYTES oam_sprites_6c
	.LOBYTES oam_sprites_6d
	.LOBYTES oam_sprites_6e
	.LOBYTES oam_sprites_6f
	.LOBYTES oam_sprites_70
	.LOBYTES oam_sprites_71
	.LOBYTES oam_sprites_72
	.LOBYTES oam_sprites_73
	.LOBYTES oam_sprites_74
	.LOBYTES oam_sprites_75
	.LOBYTES oam_sprites_76
	.LOBYTES oam_sprites_77
	.LOBYTES oam_sprites_78
	.LOBYTES oam_sprites_79
	.LOBYTES oam_sprites_7a
	.LOBYTES oam_sprites_7b
	.LOBYTES oam_sprites_7c
	.LOBYTES oam_sprites_7d
	.LOBYTES oam_sprites_7e
	.LOBYTES oam_sprites_7f
	.LOBYTES oam_sprites_80
	.LOBYTES oam_sprites_81
	.LOBYTES oam_sprites_82
	.LOBYTES oam_sprites_83
	.LOBYTES oam_sprites_84
	.LOBYTES oam_sprites_85
	.LOBYTES oam_sprites_86
	.LOBYTES oam_sprites_87
	.LOBYTES oam_sprites_88
	.LOBYTES oam_sprites_89
	.LOBYTES oam_sprites_8a
	.LOBYTES oam_sprites_8b
	.LOBYTES oam_sprites_8c
	.LOBYTES oam_sprites_8d
	.LOBYTES oam_sprites_8e
	.LOBYTES oam_sprites_8f
	.LOBYTES oam_sprites_90
	.LOBYTES oam_sprites_91
	.LOBYTES oam_sprites_92
	.LOBYTES oam_sprites_93
	.LOBYTES oam_sprites_94
	.LOBYTES oam_sprites_95
	.LOBYTES oam_sprites_96
	.LOBYTES oam_sprites_97
	.LOBYTES oam_sprites_98
	.LOBYTES oam_sprites_99
	.LOBYTES oam_sprites_9a
	.LOBYTES oam_sprites_9b
	.LOBYTES oam_sprites_9c
	.LOBYTES oam_sprites_9d
	.LOBYTES oam_sprites_9e
	.LOBYTES oam_sprites_9f
	.LOBYTES oam_sprites_a0
	.LOBYTES oam_sprites_a1
	.LOBYTES oam_sprites_a2
	.LOBYTES oam_sprites_a3
	.LOBYTES oam_sprites_a4
	.LOBYTES oam_sprites_a5
	.LOBYTES oam_sprites_a6
	.LOBYTES oam_sprites_a7
	.LOBYTES oam_sprites_a8
	.LOBYTES oam_sprites_a9
	.LOBYTES oam_sprites_aa
	.LOBYTES oam_sprites_ab
	.LOBYTES oam_sprites_ac
	.LOBYTES oam_sprites_ad
	.LOBYTES oam_sprites_ae
	.LOBYTES oam_sprites_af
	.LOBYTES oam_sprites_b0
	.LOBYTES oam_sprites_b1
	.LOBYTES oam_sprites_b2
	.LOBYTES oam_sprites_b3
	.LOBYTES oam_sprites_b4
	.LOBYTES oam_sprites_b5
	.LOBYTES oam_sprites_b6
	.LOBYTES oam_sprites_b7
	.LOBYTES oam_sprites_b8
	.LOBYTES oam_sprites_b9
	.LOBYTES oam_sprites_ba
	.LOBYTES oam_sprites_bb
	.LOBYTES oam_sprites_bc
	.LOBYTES oam_sprites_bd
	.LOBYTES oam_sprites_be
	.LOBYTES oam_sprites_bf
	.LOBYTES oam_sprites_c0
	.LOBYTES oam_sprites_c1
	.LOBYTES oam_sprites_c2
	.LOBYTES oam_sprites_c3
	.LOBYTES oam_sprites_c4
	.LOBYTES oam_sprites_c5
	.LOBYTES oam_sprites_c6
	.LOBYTES oam_sprites_c7
	.LOBYTES oam_sprites_c8
	.LOBYTES oam_sprites_c9
	.LOBYTES oam_sprites_ca
	.LOBYTES oam_sprites_cb
	.LOBYTES oam_sprites_cc
	.LOBYTES oam_sprites_cd
	.LOBYTES oam_sprites_ce
	.LOBYTES oam_sprites_cf
	.LOBYTES oam_sprites_d0
	.LOBYTES oam_sprites_d1
	.LOBYTES oam_sprites_d2
	.LOBYTES oam_sprites_d3
	.LOBYTES oam_sprites_d4
	.LOBYTES oam_sprites_d5
	.LOBYTES oam_sprites_d6
	.LOBYTES oam_sprites_d7
	.LOBYTES oam_sprites_d8
	.LOBYTES oam_sprites_d9
	.LOBYTES oam_sprites_da
	.LOBYTES oam_sprites_db
	.LOBYTES oam_sprites_dc
	.LOBYTES oam_sprites_dd
	.LOBYTES oam_sprites_de
	.LOBYTES oam_sprites_df
	.LOBYTES oam_sprites_e0
	.LOBYTES oam_sprites_e1
	.LOBYTES oam_sprites_e2
	.LOBYTES oam_sprites_e3
	.LOBYTES oam_sprites_e4
	.LOBYTES oam_sprites_e5
	.LOBYTES oam_sprites_e6
	.LOBYTES oam_sprites_e7
	.LOBYTES oam_sprites_e8
	.LOBYTES oam_sprites_e9
	.LOBYTES oam_sprites_ea
	.LOBYTES oam_sprites_eb
	.LOBYTES oam_sprites_ec
	.LOBYTES oam_sprites_ed
	.LOBYTES oam_sprites_ee
	.LOBYTES oam_sprites_ef
	.LOBYTES oam_sprites_f0
	.LOBYTES oam_sprites_f1
	.LOBYTES oam_sprites_f2
	.LOBYTES oam_sprites_f3
	.LOBYTES oam_sprites_f4
	.LOBYTES oam_sprites_f5
	.LOBYTES oam_sprites_f6
	.LOBYTES oam_sprites_f7
	.LOBYTES oam_sprites_f8
	.LOBYTES oam_sprites_f9
	.LOBYTES oam_sprites_fa
	.LOBYTES oam_sprites_fb
	.LOBYTES oam_sprites_fc
	.LOBYTES oam_sprites_fd
	.LOBYTES oam_sprites_fe
	.LOBYTES oam_sprites_ff

oam_sprites_hi_pointers:
	.HIBYTES oam_sprites_00
	.HIBYTES oam_sprites_01
	.HIBYTES oam_sprites_02
	.HIBYTES oam_sprites_03
	.HIBYTES oam_sprites_04
	.HIBYTES oam_sprites_05
	.HIBYTES oam_sprites_06
	.HIBYTES oam_sprites_07
	.HIBYTES oam_sprites_08
	.HIBYTES oam_sprites_09
	.HIBYTES oam_sprites_0a
	.HIBYTES oam_sprites_0b
	.HIBYTES oam_sprites_0c
	.HIBYTES oam_sprites_0d
	.HIBYTES oam_sprites_0e
	.HIBYTES oam_sprites_0f
	.HIBYTES oam_sprites_10
	.HIBYTES oam_sprites_11
	.HIBYTES oam_sprites_12
	.HIBYTES oam_sprites_13
	.HIBYTES oam_sprites_14
	.HIBYTES oam_sprites_15
	.HIBYTES oam_sprites_16
	.HIBYTES oam_sprites_17
	.HIBYTES oam_sprites_18
	.HIBYTES oam_sprites_19
	.HIBYTES oam_sprites_1a
	.HIBYTES oam_sprites_1b
	.HIBYTES oam_sprites_1c
	.HIBYTES oam_sprites_1d
	.HIBYTES oam_sprites_1e
	.HIBYTES oam_sprites_1f
	.HIBYTES oam_sprites_20
	.HIBYTES oam_sprites_21
	.HIBYTES oam_sprites_22
	.HIBYTES oam_sprites_23
	.HIBYTES oam_sprites_24
	.HIBYTES oam_sprites_25
	.HIBYTES oam_sprites_26
	.HIBYTES oam_sprites_27
	.HIBYTES oam_sprites_28
	.HIBYTES oam_sprites_29
	.HIBYTES oam_sprites_2a
	.HIBYTES oam_sprites_2b
	.HIBYTES oam_sprites_2c
	.HIBYTES oam_sprites_2d
	.HIBYTES oam_sprites_2e
	.HIBYTES oam_sprites_2f
	.HIBYTES oam_sprites_30
	.HIBYTES oam_sprites_31
	.HIBYTES oam_sprites_32
	.HIBYTES oam_sprites_33
	.HIBYTES oam_sprites_34
	.HIBYTES oam_sprites_35
	.HIBYTES oam_sprites_36
	.HIBYTES oam_sprites_37
	.HIBYTES oam_sprites_38
	.HIBYTES oam_sprites_39
	.HIBYTES oam_sprites_3a
	.HIBYTES oam_sprites_3b
	.HIBYTES oam_sprites_3c
	.HIBYTES oam_sprites_3d
	.HIBYTES oam_sprites_3e
	.HIBYTES oam_sprites_3f
	.HIBYTES oam_sprites_40
	.HIBYTES oam_sprites_41
	.HIBYTES oam_sprites_42
	.HIBYTES oam_sprites_43
	.HIBYTES oam_sprites_44
	.HIBYTES oam_sprites_45
	.HIBYTES oam_sprites_46
	.HIBYTES oam_sprites_47
	.HIBYTES oam_sprites_48
	.HIBYTES oam_sprites_49
	.HIBYTES oam_sprites_4a
	.HIBYTES oam_sprites_4b
	.HIBYTES oam_sprites_4c
	.HIBYTES oam_sprites_4d
	.HIBYTES oam_sprites_4e
	.HIBYTES oam_sprites_4f
	.HIBYTES oam_sprites_50
	.HIBYTES oam_sprites_51
	.HIBYTES oam_sprites_52
	.HIBYTES oam_sprites_53
	.HIBYTES oam_sprites_54
	.HIBYTES oam_sprites_55
	.HIBYTES oam_sprites_56
	.HIBYTES oam_sprites_57
	.HIBYTES oam_sprites_58
	.HIBYTES oam_sprites_59
	.HIBYTES oam_sprites_5a
	.HIBYTES oam_sprites_5b
	.HIBYTES oam_sprites_5c
	.HIBYTES oam_sprites_5d
	.HIBYTES oam_sprites_5e
	.HIBYTES oam_sprites_5f
	.HIBYTES oam_sprites_60
	.HIBYTES oam_sprites_61
	.HIBYTES oam_sprites_62
	.HIBYTES oam_sprites_63
	.HIBYTES oam_sprites_64
	.HIBYTES oam_sprites_65
	.HIBYTES oam_sprites_66
	.HIBYTES oam_sprites_67
	.HIBYTES oam_sprites_68
	.HIBYTES oam_sprites_69
	.HIBYTES oam_sprites_6a
	.HIBYTES oam_sprites_6b
	.HIBYTES oam_sprites_6c
	.HIBYTES oam_sprites_6d
	.HIBYTES oam_sprites_6e
	.HIBYTES oam_sprites_6f
	.HIBYTES oam_sprites_70
	.HIBYTES oam_sprites_71
	.HIBYTES oam_sprites_72
	.HIBYTES oam_sprites_73
	.HIBYTES oam_sprites_74
	.HIBYTES oam_sprites_75
	.HIBYTES oam_sprites_76
	.HIBYTES oam_sprites_77
	.HIBYTES oam_sprites_78
	.HIBYTES oam_sprites_79
	.HIBYTES oam_sprites_7a
	.HIBYTES oam_sprites_7b
	.HIBYTES oam_sprites_7c
	.HIBYTES oam_sprites_7d
	.HIBYTES oam_sprites_7e
	.HIBYTES oam_sprites_7f
	.HIBYTES oam_sprites_80
	.HIBYTES oam_sprites_81
	.HIBYTES oam_sprites_82
	.HIBYTES oam_sprites_83
	.HIBYTES oam_sprites_84
	.HIBYTES oam_sprites_85
	.HIBYTES oam_sprites_86
	.HIBYTES oam_sprites_87
	.HIBYTES oam_sprites_88
	.HIBYTES oam_sprites_89
	.HIBYTES oam_sprites_8a
	.HIBYTES oam_sprites_8b
	.HIBYTES oam_sprites_8c
	.HIBYTES oam_sprites_8d
	.HIBYTES oam_sprites_8e
	.HIBYTES oam_sprites_8f
	.HIBYTES oam_sprites_90
	.HIBYTES oam_sprites_91
	.HIBYTES oam_sprites_92
	.HIBYTES oam_sprites_93
	.HIBYTES oam_sprites_94
	.HIBYTES oam_sprites_95
	.HIBYTES oam_sprites_96
	.HIBYTES oam_sprites_97
	.HIBYTES oam_sprites_98
	.HIBYTES oam_sprites_99
	.HIBYTES oam_sprites_9a
	.HIBYTES oam_sprites_9b
	.HIBYTES oam_sprites_9c
	.HIBYTES oam_sprites_9d
	.HIBYTES oam_sprites_9e
	.HIBYTES oam_sprites_9f
	.HIBYTES oam_sprites_a0
	.HIBYTES oam_sprites_a1
	.HIBYTES oam_sprites_a2
	.HIBYTES oam_sprites_a3
	.HIBYTES oam_sprites_a4
	.HIBYTES oam_sprites_a5
	.HIBYTES oam_sprites_a6
	.HIBYTES oam_sprites_a7
	.HIBYTES oam_sprites_a8
	.HIBYTES oam_sprites_a9
	.HIBYTES oam_sprites_aa
	.HIBYTES oam_sprites_ab
	.HIBYTES oam_sprites_ac
	.HIBYTES oam_sprites_ad
	.HIBYTES oam_sprites_ae
	.HIBYTES oam_sprites_af
	.HIBYTES oam_sprites_b0
	.HIBYTES oam_sprites_b1
	.HIBYTES oam_sprites_b2
	.HIBYTES oam_sprites_b3
	.HIBYTES oam_sprites_b4
	.HIBYTES oam_sprites_b5
	.HIBYTES oam_sprites_b6
	.HIBYTES oam_sprites_b7
	.HIBYTES oam_sprites_b8
	.HIBYTES oam_sprites_b9
	.HIBYTES oam_sprites_ba
	.HIBYTES oam_sprites_bb
	.HIBYTES oam_sprites_bc
	.HIBYTES oam_sprites_bd
	.HIBYTES oam_sprites_be
	.HIBYTES oam_sprites_bf
	.HIBYTES oam_sprites_c0
	.HIBYTES oam_sprites_c1
	.HIBYTES oam_sprites_c2
	.HIBYTES oam_sprites_c3
	.HIBYTES oam_sprites_c4
	.HIBYTES oam_sprites_c5
	.HIBYTES oam_sprites_c6
	.HIBYTES oam_sprites_c7
	.HIBYTES oam_sprites_c8
	.HIBYTES oam_sprites_c9
	.HIBYTES oam_sprites_ca
	.HIBYTES oam_sprites_cb
	.HIBYTES oam_sprites_cc
	.HIBYTES oam_sprites_cd
	.HIBYTES oam_sprites_ce
	.HIBYTES oam_sprites_cf
	.HIBYTES oam_sprites_d0
	.HIBYTES oam_sprites_d1
	.HIBYTES oam_sprites_d2
	.HIBYTES oam_sprites_d3
	.HIBYTES oam_sprites_d4
	.HIBYTES oam_sprites_d5
	.HIBYTES oam_sprites_d6
	.HIBYTES oam_sprites_d7
	.HIBYTES oam_sprites_d8
	.HIBYTES oam_sprites_d9
	.HIBYTES oam_sprites_da
	.HIBYTES oam_sprites_db
	.HIBYTES oam_sprites_dc
	.HIBYTES oam_sprites_dd
	.HIBYTES oam_sprites_de
	.HIBYTES oam_sprites_df
	.HIBYTES oam_sprites_e0
	.HIBYTES oam_sprites_e1
	.HIBYTES oam_sprites_e2
	.HIBYTES oam_sprites_e3
	.HIBYTES oam_sprites_e4
	.HIBYTES oam_sprites_e5
	.HIBYTES oam_sprites_e6
	.HIBYTES oam_sprites_e7
	.HIBYTES oam_sprites_e8
	.HIBYTES oam_sprites_e9
	.HIBYTES oam_sprites_ea
	.HIBYTES oam_sprites_eb
	.HIBYTES oam_sprites_ec
	.HIBYTES oam_sprites_ed
	.HIBYTES oam_sprites_ee
	.HIBYTES oam_sprites_ef
	.HIBYTES oam_sprites_f0
	.HIBYTES oam_sprites_f1
	.HIBYTES oam_sprites_f2
	.HIBYTES oam_sprites_f3
	.HIBYTES oam_sprites_f4
	.HIBYTES oam_sprites_f5
	.HIBYTES oam_sprites_f6
	.HIBYTES oam_sprites_f7
	.HIBYTES oam_sprites_f8
	.HIBYTES oam_sprites_f9
	.HIBYTES oam_sprites_fa
	.HIBYTES oam_sprites_fb
	.HIBYTES oam_sprites_fc
	.HIBYTES oam_sprites_fd
	.HIBYTES oam_sprites_fe
	.HIBYTES oam_sprites_ff
